[project]
name = "huhu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=8.3.3",
    "shellingham>=1.5.4",
    "tinydb>=4.8.0",
    "typer>=0.12.5",
]
